<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="35" passed="29" failed="6" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-04-01T10:26:17 BDT" name="All Test Suite" finished-at="2024-04-01T10:26:44 BDT" duration-ms="26979">
    <groups>
    </groups>
    <test started-at="2024-04-01T10:26:17 BDT" name="G:/Project/Skyscanner_API" finished-at="2024-04-01T10:26:44 BDT" duration-ms="26979">
      <class name="Flights_Indicative_Prices_POST">
        <test-method is-config="true" signature="setup()[pri:0, instance:Flights_Indicative_Prices_POST@3943a2be]" started-at="2024-04-01T10:26:17 BDT" name="setup" finished-at="2024-04-01T10:26:18 BDT" duration-ms="594" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testMissingDestinationPlace()[pri:1, instance:Flights_Indicative_Prices_POST@3943a2be]" started-at="2024-04-01T10:26:18 BDT" name="testMissingDestinationPlace" finished-at="2024-04-01T10:26:20 BDT" duration-ms="2030" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMissingDestinationPlace -->
        <test-method signature="testInvalidDateRange()[pri:2, instance:Flights_Indicative_Prices_POST@3943a2be]" started-at="2024-04-01T10:26:20 BDT" name="testInvalidDateRange" finished-at="2024-04-01T10:26:21 BDT" duration-ms="726" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidDateRange -->
        <test-method signature="testWithoutOptionalParameter()[pri:3, instance:Flights_Indicative_Prices_POST@3943a2be]" started-at="2024-04-01T10:26:21 BDT" name="testWithoutOptionalParameter" finished-at="2024-04-01T10:26:22 BDT" duration-ms="1083" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWithoutOptionalParameter -->
        <test-method signature="testHTTPMethod()[pri:4, instance:Flights_Indicative_Prices_POST@3943a2be]" started-at="2024-04-01T10:26:22 BDT" name="testHTTPMethod" finished-at="2024-04-01T10:26:23 BDT" duration-ms="940" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testHTTPMethod -->
        <test-method signature="testUnauthorizedAccess()[pri:5, instance:Flights_Indicative_Prices_POST@3943a2be]" started-at="2024-04-01T10:26:23 BDT" name="testUnauthorizedAccess" finished-at="2024-04-01T10:26:23 BDT" duration-ms="520" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUnauthorizedAccess -->
        <test-method signature="testInvalidURL()[pri:6, instance:Flights_Indicative_Prices_POST@3943a2be]" started-at="2024-04-01T10:26:23 BDT" name="testInvalidURL" finished-at="2024-04-01T10:26:24 BDT" duration-ms="910" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidURL -->
        <test-method signature="testInvalidMethod()[pri:7, instance:Flights_Indicative_Prices_POST@3943a2be]" started-at="2024-04-01T10:26:24 BDT" name="testInvalidMethod" finished-at="2024-04-01T10:26:25 BDT" duration-ms="637" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [405] but found [501]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [405] but found [501]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at Flights_Indicative_Prices_POST.testInvalidMethod(Flights_Indicative_Prices_POST.java:217)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidMethod -->
        <test-method signature="testWithInvalidLocale()[pri:8, instance:Flights_Indicative_Prices_POST@3943a2be]" started-at="2024-04-01T10:26:25 BDT" name="testWithInvalidLocale" finished-at="2024-04-01T10:26:25 BDT" duration-ms="611" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWithInvalidLocale -->
        <test-method signature="testWithoutMarketParameter()[pri:9, instance:Flights_Indicative_Prices_POST@3943a2be]" started-at="2024-04-01T10:26:25 BDT" name="testWithoutMarketParameter" finished-at="2024-04-01T10:26:26 BDT" duration-ms="534" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWithoutMarketParameter -->
        <test-method signature="testWithoutCurrencyParameter()[pri:10, instance:Flights_Indicative_Prices_POST@3943a2be]" started-at="2024-04-01T10:26:26 BDT" name="testWithoutCurrencyParameter" finished-at="2024-04-01T10:26:26 BDT" duration-ms="606" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWithoutCurrencyParameter -->
      </class> <!-- Flights_Indicative_Prices_POST -->
      <class name="Geo_GET">
        <test-method is-config="true" signature="setup()[pri:0, instance:Geo_GET@69fb6037]" started-at="2024-04-01T10:26:26 BDT" name="setup" finished-at="2024-04-01T10:26:26 BDT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testHTTPMethod()[pri:1, instance:Geo_GET@69fb6037]" started-at="2024-04-01T10:26:26 BDT" name="testHTTPMethod" finished-at="2024-04-01T10:26:29 BDT" duration-ms="2112" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testHTTPMethod -->
        <test-method signature="testMissingLocale()[pri:2, instance:Geo_GET@69fb6037]" started-at="2024-04-01T10:26:29 BDT" name="testMissingLocale" finished-at="2024-04-01T10:26:29 BDT" duration-ms="683" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMissingLocale -->
        <test-method signature="testUnauthorizedAccess()[pri:3, instance:Geo_GET@69fb6037]" started-at="2024-04-01T10:26:29 BDT" name="testUnauthorizedAccess" finished-at="2024-04-01T10:26:30 BDT" duration-ms="597" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUnauthorizedAccess -->
        <test-method signature="testInvalidURL()[pri:4, instance:Geo_GET@69fb6037]" started-at="2024-04-01T10:26:30 BDT" name="testInvalidURL" finished-at="2024-04-01T10:26:30 BDT" duration-ms="612" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidURL -->
        <test-method signature="testInvalidMethod()[pri:5, instance:Geo_GET@69fb6037]" started-at="2024-04-01T10:26:30 BDT" name="testInvalidMethod" finished-at="2024-04-01T10:26:31 BDT" duration-ms="633" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[1 expectation failed.
Expected status code <405> but was <501>.
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <405> but was <501>.

at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:135)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:143)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
at Geo_GET.testInvalidMethod(Geo_GET.java:131)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidMethod -->
      </class> <!-- Geo_GET -->
      <class name="Autosuggest_POST">
        <test-method is-config="true" signature="setup()[pri:0, instance:Autosuggest_POST@87a85e1]" started-at="2024-04-01T10:26:35 BDT" name="setup" finished-at="2024-04-01T10:26:35 BDT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testHTTPMethod()[pri:1, instance:Autosuggest_POST@87a85e1]" started-at="2024-04-01T10:26:35 BDT" name="testHTTPMethod" finished-at="2024-04-01T10:26:35 BDT" duration-ms="550" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testHTTPMethod -->
        <test-method signature="testInvalidSearchTerm()[pri:2, instance:Autosuggest_POST@87a85e1]" started-at="2024-04-01T10:26:35 BDT" name="testInvalidSearchTerm" finished-at="2024-04-01T10:26:36 BDT" duration-ms="645" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidSearchTerm -->
        <test-method signature="testInvalidMethod()[pri:3, instance:Autosuggest_POST@87a85e1]" started-at="2024-04-01T10:26:36 BDT" name="testInvalidMethod" finished-at="2024-04-01T10:26:37 BDT" duration-ms="413" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidMethod -->
        <test-method signature="testUnauthorizedAccess()[pri:4, instance:Autosuggest_POST@87a85e1]" started-at="2024-04-01T10:26:37 BDT" name="testUnauthorizedAccess" finished-at="2024-04-01T10:26:37 BDT" duration-ms="802" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUnauthorizedAccess -->
        <test-method signature="testInvalidURL()[pri:5, instance:Autosuggest_POST@87a85e1]" started-at="2024-04-01T10:26:37 BDT" name="testInvalidURL" finished-at="2024-04-01T10:26:38 BDT" duration-ms="457" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidURL -->
        <test-method signature="testExeceedingLimit()[pri:6, instance:Autosuggest_POST@87a85e1]" started-at="2024-04-01T10:26:38 BDT" name="testExeceedingLimit" finished-at="2024-04-01T10:26:38 BDT" duration-ms="679" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [400] but found [422]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [400] but found [422]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at Autosuggest_POST.testExeceedingLimit(Autosuggest_POST.java:194)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testExeceedingLimit -->
        <test-method signature="testInvalidLocale()[pri:7, instance:Autosuggest_POST@87a85e1]" started-at="2024-04-01T10:26:38 BDT" name="testInvalidLocale" finished-at="2024-04-01T10:26:39 BDT" duration-ms="548" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidLocale -->
        <test-method signature="testMissingMarket()[pri:8, instance:Autosuggest_POST@87a85e1]" started-at="2024-04-01T10:26:39 BDT" name="testMissingMarket" finished-at="2024-04-01T10:26:40 BDT" duration-ms="539" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [400] but found [422]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [400] but found [422]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at Autosuggest_POST.testMissingMarket(Autosuggest_POST.java:248)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMissingMarket -->
      </class> <!-- Autosuggest_POST -->
      <class name="Geo_POST">
        <test-method is-config="true" signature="setup()[pri:0, instance:Geo_POST@36d585c]" started-at="2024-04-01T10:26:31 BDT" name="setup" finished-at="2024-04-01T10:26:31 BDT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testInvalidIpAddress()[pri:1, instance:Geo_POST@36d585c]" started-at="2024-04-01T10:26:31 BDT" name="testInvalidIpAddress" finished-at="2024-04-01T10:26:32 BDT" duration-ms="403" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidIpAddress -->
        <test-method signature="testAdditionalField()[pri:2, instance:Geo_POST@36d585c]" started-at="2024-04-01T10:26:32 BDT" name="testAdditionalField" finished-at="2024-04-01T10:26:32 BDT" duration-ms="763" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAdditionalField -->
        <test-method signature="testUnauthorizedAccess()[pri:3, instance:Geo_POST@36d585c]" started-at="2024-04-01T10:26:32 BDT" name="testUnauthorizedAccess" finished-at="2024-04-01T10:26:33 BDT" duration-ms="625" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUnauthorizedAccess -->
        <test-method signature="testHTTPMethod()[pri:4, instance:Geo_POST@36d585c]" started-at="2024-04-01T10:26:33 BDT" name="testHTTPMethod" finished-at="2024-04-01T10:26:33 BDT" duration-ms="517" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testHTTPMethod -->
        <test-method signature="testInvalidURL()[pri:5, instance:Geo_POST@36d585c]" started-at="2024-04-01T10:26:33 BDT" name="testInvalidURL" finished-at="2024-04-01T10:26:34 BDT" duration-ms="586" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidURL -->
        <test-method signature="testInvalidMethod()[pri:6, instance:Geo_POST@36d585c]" started-at="2024-04-01T10:26:34 BDT" name="testInvalidMethod" finished-at="2024-04-01T10:26:35 BDT" duration-ms="485" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [405] but found [501]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [405] but found [501]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at Geo_POST.testInvalidMethod(Geo_POST.java:185)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidMethod -->
        <test-method signature="testInvalidLocale()[pri:7, instance:Geo_POST@36d585c]" started-at="2024-04-01T10:26:35 BDT" name="testInvalidLocale" finished-at="2024-04-01T10:26:35 BDT" duration-ms="430" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidLocale -->
      </class> <!-- Geo_POST -->
      <class name="Carriers_GET">
        <test-method is-config="true" signature="setup()[pri:0, instance:Carriers_GET@671a5887]" started-at="2024-04-01T10:26:40 BDT" name="setup" finished-at="2024-04-01T10:26:40 BDT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testUnauthorizedAccess()[pri:1, instance:Carriers_GET@671a5887]" started-at="2024-04-01T10:26:40 BDT" name="testUnauthorizedAccess" finished-at="2024-04-01T10:26:41 BDT" duration-ms="946" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUnauthorizedAccess -->
        <test-method signature="testInvalidURL()[pri:2, instance:Carriers_GET@671a5887]" started-at="2024-04-01T10:26:41 BDT" name="testInvalidURL" finished-at="2024-04-01T10:26:41 BDT" duration-ms="614" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidURL -->
        <test-method signature="testContentValidation()[pri:3, instance:Carriers_GET@671a5887]" started-at="2024-04-01T10:26:41 BDT" name="testContentValidation" finished-at="2024-04-01T10:26:43 BDT" duration-ms="1831" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testContentValidation -->
        <test-method signature="testHTTPMethod()[pri:4, instance:Carriers_GET@671a5887]" started-at="2024-04-01T10:26:43 BDT" name="testHTTPMethod" finished-at="2024-04-01T10:26:44 BDT" duration-ms="647" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testHTTPMethod -->
        <test-method signature="testInvalidMethod()[pri:5, instance:Carriers_GET@671a5887]" started-at="2024-04-01T10:26:44 BDT" name="testInvalidMethod" finished-at="2024-04-01T10:26:44 BDT" duration-ms="561" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [405] but found [501]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [405] but found [501]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at Carriers_GET.testInvalidMethod(Carriers_GET.java:136)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidMethod -->
      </class> <!-- Carriers_GET -->
    </test> <!-- G:/Project/Skyscanner_API -->
  </suite> <!-- All Test Suite -->
</testng-results>
